### ISSUE TITLE
wrong command for installing MYSQL

### ISSUE THREAD

**Issue by alainpham** [lbroudoux/chuck-norris-streams#2]
In the main readme file

actual :

oc env dc/mysqldebezium MYSQL_ROOT_PASSWORD=password MYSQL_USER=chuck MYSQL_PASSWORD=password -n chuck-movie-rental

should be 

oc set env dc/mysqldebezium MYSQL_ROOT_PASSWORD=password MYSQL_USER=chuck MYSQL_PASSWORD=password -n chuck-movie-rental

**Comment by lbroudoux** [comment]
Done ;-) Thanks @alainpham !!
